# rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-deployer
  namespace: backend
rules:
  - apiGroups: ["", "apps"]
    resources:
      - deployments
      - services
      - configmaps
      - secrets
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-deployer-binding
  namespace: backend
subjects:
  - kind: ServiceAccount
    name: ci-deployer
    namespace: backend
roleRef:
  kind: Role
  name: backend-deployer
  apiGroup: rbac.authorization.k8s.io
